site_name: Manual de LearningML
nav:
  - Introducción: 01-intro.md
  - Descripción de la plataforma LearningML: 02-descripcion.md
  - El editor de modelos de Machine Learning: editor-modelos.md
theme: 
  name: material
  language: es
markdown_extensions:
  - footnotes
